export const ActionTypes ={
    GET_NUMBER_CART : 'GET_NUMBER_CART',
    ADD_TO_CART : 'ADD_TO_CART',
    DELETE_ITEM : 'DELETE_ITEM',
    CLEAR_CART: 'CLEAR_CART',
    DECREMENT_QUANTITY: 'DECREMENT_QUANTITY',
} 


export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';

